from .tipodocumento import TipoDocumento
from .alumno import Alumno
from .area import Area
from .categoriacargo import CategoriaCargo
from .departamento import Departamento
from .especialidad import Especialidad
from .facultad import Facultad
from .grado import Grado
from .grupo import Grupo
from .materia import Materia
from .plan import Plan
from .tipodedicacion import TipoDedicacion
from .tipoespecialidad import TipoEspecialidad
from .orientacion import Orientacion
from .universidad import Universidad
from .cargo import Cargo
from .autoridad import Autoridad
