from .facultad import Facultad
from .autoridad import Autoridad
from .cargo import Cargo
from .categoria_cargo import CategoriaCargo
from .tipo_dedicacion import TipoDedicacion
from .orientacion import Orientacion
from .especialidad import Especialidad
from .tipo_especialidad import TipoEspecialidad
from .plan import Plan
from .materia import Materia
from .universidad import Universidad
from .area import Area
from .grupo import Grupo
from .grado import Grado
from .departamento import Departamento